export default {
  products: [
    {
      _id: '1',
      name: '집업 러닝 셔츠',
      category: 'Shirts',
      image: '/images/product-1.jpeg',
      price: '58,000',
      brand: '나이크',
      rating: 4.0,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: '에어팟 프로',
      cateogry: 'Device',
      image: '/images/product-2.jpeg',
      price: '329,000',
      brand: '애쁠',
      rating: 4.8,
      numReviews: 44,
      countInStock: 999,
    },
    {
      _id: '3',
      name: '반팔 셔츠',
      cateogry: 'Shirts',
      image: '/images/product-5.jpeg',
      price: '118,000',
      brand: '아디도스 셔츠',
      rating: 4.3,
      numReviews: 32,
      countInStock: 582,
    },
    {
      _id: '4',
      name: '쑤니 카메라',
      cateogry: 'Device',
      image: '/images/product-3.jpeg',
      price: '987,900',
      brand: '쑤니',
      rating: 4.8,
      numReviews: 142,
      countInStock: 555,
    },
    {
      _id: '5',
      name: '안경 SM-141',
      cateogry: 'Device',
      image: '/images/product-4.jpeg',
      price: '138,000',
      brand: '안경은 안경이다',
      rating: 4.9,
      numReviews: 14,
      countInStock: 952,
    },
    {
      _id: '6',
      name: '모니터',
      cateogry: 'Device',
      image: '/images/product-6.jpeg',
      price: '690,000',
      brand: 'Delle',
      rating: 5,
      numReviews: 59,
      countInStock: 450,
    },
  ],
};
